name: Cargo Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # rustup:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Update
  #     run: rustup update
  #   - name: Install fmt
  #     run: rustup component add rustfmt
  #   - name: Install clippy
  #     run: rustup component add clippy
  # check-fmt:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Check formatting
  #     run: cargo fmt -- --check
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run clippy
      run: cargo clippy
  builds:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build (no features)
      run: cargo build --no-default-features;
    - name: Build (default features)
      run: cargo build;
    - name: Build (std)
      run: cargo build --features std;
    - name: Build (all features)
      run: cargo build --all-features;
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test (no features)
      run: cargo test --no-default-features;
    - name: Test (default features)
      run: cargo test;
    - name: Test (std)
      run: cargo test --features std;
    - name: Test (all features)
      run: cargo test --all-features;
